version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:14
    container_name: mindroute-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mindroute
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mindroute-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 백엔드 API 서버
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mindroute-backend
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mindroute?schema=public
      - PORT=4000
      - JWT_SECRET=mindroute_dev_jwt_secret
      - ENCRYPTION_KEY=mindroute_dev_encryption_key_32char
      - ENCRYPTION_IV=mindroute_dev_iv
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mindroute-network
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  # 프론트엔드 서버
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mindroute-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - mindroute-network
    command: npm run dev
    depends_on:
      - backend

networks:
  mindroute-network:
    driver: bridge

volumes:
  postgres_data:
