version: '3.8'

services:
  # 백엔드 서비스
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/mindroute_dev
      - JWT_SECRET=your-super-secret-key-change-in-production
      - JWT_EXPIRES_IN=1h
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - ENCRYPTION_KEY=your-encryption-key-must-be-32-chars
    restart: unless-stopped

  # 프론트엔드 서비스
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  # PostgreSQL 서비스
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mindroute_dev
    restart: unless-stopped

volumes:
  postgres_data: 